server:
  port: 84
spring:
  application:
    name: elean-consumer-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://elean-7001.com:7001/eureka/,http://elean-7002.com:7002/eureka/
feign:
  hystrix:
    enabled: true