server:
  port: 8001

spring:
  application:
    name: elean-order-service
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: elean
    password: ding1234
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.elean.entities

#注册服务
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://elean-7001.com:7001/eureka/
      #defaultZone: http://elean-7001.com:7001/eureka/,http://elean-7002.com:7002/eureka/
      defaultZone: http://elean-7002.com:7002/eureka/
  instance:
    instance-id: order8001
    prefer-ip-address: true
    #向注册中心发送心跳的时间间隔
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2