server:
  port: 8000

spring:
  mvc:
    favicon:
      enable: false
  banner:
    location: classpath:static/games.jpg
  application:
    name: elean-order-service
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: elean
    password: ding1234
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.elean.entities

#注册服务
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://elean-7001.com:7001/eureka/
      defaultZone: http://elean-7001.com:7001/eureka/,http://elean-7002.com:7002/eureka/
  #修改注册中心页面的信息展示内容
  instance:
    #修改主机名称
    instance-id: order8000
    #显示ip地址
    prefer-ip-address: true