server:
  port: 9527
spring:
  application:
    name: elean-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能，利用微服务名进行路由，主要是为了再gateway上实现多个为微服务的负载均衡
          enabled: true
      routes:
        - id: payment_uri
          #uri: http://localhost:8000
          #动态路由后，匹配后提供服务的路由地址
          uri: lb://elean-order-service
          predicates:
            - Path=/order/payment/**
        - id: payment_uri2
          #uri: http://localhost:8000
          uri: lb://elean-order-service
          predicates:
            - Path=/order/port/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://elean-7001.com:7001/eureka/,http://elean-7002.com:7002/eureka/

