server:
  port: 7001

eureka:
  instance:
    hostname: elean-7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://elean-7002.com:7002/eureka/