server:
  port: 7002

eureka:
  instance:
    hostname: elean-7002.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://elean-7001.com:7001/eureka/
  server:
    #自我保护机制
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000